eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: mentorapp-admin
  datasource:
    url: jdbc:h2:file:./data/mentorapp-admin;;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
